site:
  i18n:
    class: info.magnolia.cms.i18n.DefaultI18nContentSupport
    enabled: true
    fallbackLocale: ru
    locales:
      en:
        country: ''
        enabled: true
        language: en
      ru:
        country: ''
        enabled: true
        language: ru
